# Generated by Django 4.2.4 on 2023-08-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='restaurent',
            name='img',
            field=models.ImageField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special_menu',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
