# Generated by Django 4.2.4 on 2023-08-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_gallery_restaurent_img_special_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='restaurent',
            name='title',
        ),
    ]
