# Generated by Django 4.2.4 on 2023-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_restaurent_text_remove_restaurent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default=1, upload_to='menu/'),
            preserve_default=False,
        ),
    ]
