# Generated by Django 4.2.4 on 2023-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='testiminional',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
